# Generated by Django 4.1.7 on 2023-04-02 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attend',
            new_name='Status',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendance',
            new_name='status',
        ),
    ]
