# Generated by Django 4.1.7 on 2023-04-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_attendance_options_alter_status_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='course',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='level',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
    ]
