# Generated by Django 4.1.7 on 2023-04-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_attendance_course_attendance_level_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.course'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.level'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.status'),
        ),
    ]
