# Generated by Django 4.1.7 on 2023-04-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_attendance_course_alter_attendance_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='level',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=300),
        ),
    ]
