# Generated by Django 4.1.7 on 2023-04-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_attendance_course_alter_attendance_level_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
