# Generated by Django 4.1.7 on 2023-04-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='status',
            new_name='category',
        ),
    ]
